<!DOCTYPE html>
<html lang="en">
<head>
<!--
# TEAM ATOM WEDDING
# MESSAGE BEGIN
~
WELCOME BACK, COMMANDER.
I SEE YOU HAVE DISCOVERED THE HIDDEN MESSAGE.
THIS IS GOOD. TIME IS SHORT, AND WE NEED EVERY MINUTE WE'VE GOT.
HEAD TO http://i.imgur.com/0CCC6Fj.png TO UNLOCK THE SECRET LAUNCH CODES.
GOOD LUCK, COMMANDER. YOU'LL NEED IT.
# MESSAGE END
-->
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name='title' content='Team aTom Online'>
	<meta name='description' content='The home of Team aTom - on the internet'>
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="css/style.css">
	<title>Team aTom Online</title>
</head>
<body>
	{% block content %}{% endblock %}
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
	<script src="https://cdn.socket.io/socket.io-1.3.5.js"></script>
	<script src='js/showdown.min.js'></script>
	<script src='js/client.js'></script>
</body>
</html>
