<!DOCTYPE html>
<html lang="en">
<head>
<!--
# TEAM ATOM WEDDING
# MESSAGE BEGIN
~
WELCOME BACK, COMMANDER.
I SEE YOU HAVE DISCOVERED THE HIDDEN MESSAGE.
THIS IS GOOD. TIME IS SHORT, AND WE NEED EVERY MINUTE WE'VE GOT.
HEAD TO http://i.imgur.com/0CCC6Fj.png TO UNLOCK THE SECRET LAUNCH CODES.
GOOD LUCK, COMMANDER. YOU'LL NEED IT.
# MESSAGE END
-->
	<meta charset="UTF-8">
	<meta name='title' content='Team aTom Online'>
	<meta name='description' content='The home of Team aTom - on the internet'>
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<link rel="stylesheet" type="text/css" href="css/style.css">
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-7s5uDGW3AHqw6xtJmNNtr+OBRJUlgkNJEo78P4b0yRw= sha512-nNo+yCHEyn0smMxSswnf/OnX6/KwJuZTlNZBjauKhTK0c+zT+q5JOCx0UFhXQ6rJR9jg6Es8gPuD2uZcYDLqSw==" crossorigin="anonymous">
	<title>Team aTom Online</title>
</head>
<body>
	{% block content %}{% endblock %}
</body>
</html>
